### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by lukemagdalin** [natowb/iPotions#3]
While launching the server I get this error code

[21:39:18 ERROR]: Error occurred while enabling iPotions v1.3 (Is it up to date?)
java.lang.NoSuchFieldError: LUCK

I am running papermc 1.8.8 with java jre 8

**Comment by natowb** [comment]
Hi @lukemagdalin 

It appears 1.8 builds are more of a pain then initially thought, adding 1.8 support will need a bit of a rework in the plugin which will take longer than expected. for now ill remove 1.8 support from the spigot page and will notify you when its availiable.

Apologies,
Natowb

**Comment by lukemagdalin** [comment]
ok, sorry it's taken me so long to get back to this. I haven't been checking my notifications. I have already found a replacement after hours of searching. Although I will try this again once you finish it. good luck!
